# Generated by Django 5.1.5 on 2025-03-08 08:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('tech', 'Tech'), ('healthcare', 'Healthcare'), ('finance', 'Finance'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=20)),
                ('funding_round', models.CharField(choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('ipo', 'IPO')], default='pre_seed', max_length=20)),
                ('funding_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pitch_deck', models.FileField(blank=True, null=True, upload_to='pitch_decks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'ppt', 'pptx'])])),
                ('business_plan_summary', models.TextField(help_text='Provide a short summary of your business plan (max 1000 characters)', max_length=1000)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor_views', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'investor'}, related_name='viewed_applications', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(limit_choices_to={'user_type': 'startup'}, on_delete=django.db.models.deletion.CASCADE, related_name='startup_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
