# Generated by Django 5.1.5 on 2025-03-10 03:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount_invested', models.DecimalField(decimal_places=2, max_digits=15)),
                ('investment_type', models.CharField(choices=[('equity', 'Equity'), ('debt', 'Debt'), ('grant', 'Grant'), ('other', 'Other')], default='equity', max_length=10)),
                ('equity_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment', to='applications.applicationmodel')),
                ('investor', models.ForeignKey(limit_choices_to={'user_type': 'investor'}, on_delete=django.db.models.deletion.CASCADE, related_name='investor_investments', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(limit_choices_to={'user_type': 'startup'}, on_delete=django.db.models.deletion.CASCADE, related_name='startup_funding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
