# Generated by Django 5.1.5 on 2025-03-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('investment_focus', models.CharField(max_length=100)),
                ('available_funds', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
